name: CI Proyecto 4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -padmin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_HOST: 127.0.0.1
      MYSQL_DB: testdb

    steps:
      - uses: actions/checkout@v3

      - name: Esperar a que MySQL esté listo
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -padmin --silent; then
              echo "MySQL está listo 🚀"
              break
            fi
            echo "Esperando MySQL..."
            sleep 5
          done

      - name: Ejecutar script backup
        run: |
          chmod +x ./backup_mysql.sh
          ./backup_mysql.sh
