name: Proyecto4 CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  devops-automation:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Chequear repositorio
        uses: actions/checkout@v4

      - name: Instalar Python y dependencias
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip3 install flask requests

      - name: Ejecutar backup MySQL
        run: |
          chmod +x ./backup_mysql.sh
          ./backup_mysql.sh
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: rootpassword
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: testdb

      - name: Levantar servidor simulado
        run: |
          nohup python3 ./server_simulado.py &
          sleep 3

      - name: Ejecutar chequeo de logs y endpoints
        run: |
          python3 ./check_logs_endpoints.py
